/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 00e2a4d985f6a14fc457f144047fa377)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SIGNAL_ROOM: DurableObjectNamespace<import("./worker/index").SignalRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "SignalRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
