/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a664f6b37953ccb7d4f62496d975b968)
interface __BaseEnv_Env {
	AI: Ai;
	ASSETS: Fetcher;
	AI_RENDER_ENABLED: "true";
	RENDER_LEDGER: DurableObjectNamespace<import("./worker/index").RenderLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "RenderLedger";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_RENDER_ENABLED">> {}
}
