/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9f92086d99c433ebbb3609808d4ab958)
interface __BaseEnv_Env {
	DB: D1Database;
	CREATE_LIMITER: RateLimit;
	STEP_LIMITER: RateLimit;
	AI: Ai;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
